spring.application.name=jpaProject

spring.datasource.url=jdbc:h2:file:./data/jpadb;AUTO_SERVER=TRUE;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=outback
spring.datasource.password=dollar

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true